# Specify the version of docker compose.
version: "3.9"

services:
  # Container for Laravel
  app:
    # Connect 8000 port of the host to 80 port of the container.
    ports:
      - "8000:80"
    build: ./docker/app
    container_name: laravel_app
    volumes:
      - ./:/var/www/html/

  # Container for MySql.
  db:
    build: ./docker/db
    container_name: laravel_db
    environment:
      # >>> Should be changed >>>
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
      # <<< Should be changed <<<
      TZ: "Europe/London"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306